# Generated by Django 4.2.20 on 2026-03-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_user_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_cured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('hospital', 'name')},
        ),
    ]
