# Generated by Django 4.2.20 on 2026-03-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_patient_is_cured_alter_department_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_cured',
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='is_cured',
            field=models.BooleanField(default=False),
        ),
    ]
