# Generated by Django 4.2.20 on 2026-03-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_remove_patient_is_cured_patientvisit_is_cured'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='discharge_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
