# Generated by Django 4.2.20 on 2026-03-19 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_patientvisit_discharge_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='department',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hospital',
        ),
        migrations.AlterModelOptions(
            name='patientvisit',
            options={'ordering': ['-visit_date']},
        ),
        migrations.RemoveField(
            model_name='patientvisit',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='sharedreport',
            name='patient',
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='patient_id',
            field=models.CharField(db_index=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='patient_name',
            field=models.CharField(default='sa', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='patientvisit',
            index=models.Index(fields=['patient_id'], name='hospital_pa_patient_ecfb07_idx'),
        ),
        migrations.AddIndex(
            model_name='patientvisit',
            index=models.Index(fields=['hospital', 'department'], name='hospital_pa_hospita_083fdc_idx'),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
