# Generated by Django 4.2.20 on 2026-03-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_remove_patient_department_remove_patient_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientvisit',
            name='is_cured',
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='status',
            field=models.CharField(choices=[('cured', 'Cured'), ('dead', 'Deceased'), ('shifted', 'Shifted')], default='cured', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='discharge_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
