# Generated by Django 4.2.20 on 2026-03-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_remove_patientvisit_is_cured_patientvisit_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedreport',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sharedreport',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
