# Generated by Django 4.2.20 on 2026-03-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_doctor_address_doctor_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
