# Generated by Django 4.2.20 on 2026-03-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_alter_doctor_doctor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_id',
        ),
    ]
