# Generated by Django 4.2.20 on 2026-03-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_remove_doctor_doctor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='previous_hospital',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='working_days',
        ),
    ]
