# Generated by Django 4.2.20 on 2026-03-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_doctor_address_doctor_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='report_type',
            field=models.CharField(choices=[('blood', 'Blood Report'), ('scan', 'Scan Report'), ('discharge', 'Discharge Summary'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
